import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { ThemeProvider } from "next-themes"
import { Suspense } from "react"
import { ModeToggle } from "@/components/mode-toggle"
import SignOutButton from "@/components/sign-out-button"
import { Spinner } from "@/components/ui/spinner"
import "./globals.css"
import Image from "next/image"
import Link from "next/link"
import GradientText from "@/components/react-bits/GradientText"
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "RP-World",
  description: "Generated by create next app",
  appleWebApp: {
    title: "RP-World",
  },
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="flex items-center justify-between p-2">
            <Link href="/" className="flex items-center gap-2">
              <Image
                src="/logo.png"
                alt="Logo"
                width={36}
                height={36}
                loading="eager"
              />
              <GradientText className="font-serif text-3xl">
                RP-WORLD
              </GradientText>
            </Link>
            <div className="flex items-center gap-2">
              <ModeToggle />
              <SignOutButton />
            </div>
          </header>
          <Suspense
            fallback={
              <div className="mt-4 flex items-center justify-center">
                <Spinner />
              </div>
            }
          >
            {children}
          </Suspense>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
