import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { ThemeProvider } from "next-themes"
import { Suspense } from "react"
import "./globals.css"
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs"
import { Button } from "@/components/ui/button"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Rahul Patil",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            {/* Clerk components go here */}
            <header className="flex h-16 items-center justify-end gap-4 p-4">
              <Suspense>
                <SignedOut>
                  <SignInButton />
                  <SignUpButton>
                    <Button className="h-10 cursor-pointer rounded-full bg-[#6c47ff] px-4 font-medium text-ceramic-white text-sm sm:h-12 sm:px-5 sm:text-base">
                      Sign Up
                    </Button>
                  </SignUpButton>
                </SignedOut>
              </Suspense>
              <Suspense>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </Suspense>
            </header>
          </ClerkProvider>
          <Suspense>{children}</Suspense>
        </ThemeProvider>
      </body>
    </html>
  )
}
